USE [master]
GO

-- create database primary file group and log
CREATE DATABASE $(db_name) ON  PRIMARY
( NAME = '$(db_name)_primary',
  FILENAME = N'$(db_path)primary.ndf',
  SIZE = 1GB ,
  MAXSIZE = 25GB ,
  FILEGROWTH = 1GB)
LOG ON
( NAME = '$(db_name)_log',
  FILENAME = '$(log_path)$(db_name)_log.ldf',
  SIZE = 1GB ,
  MAXSIZE = 25GB ,
  FILEGROWTH = 1GB)
GO

-- set compatibility to sql server 2016
ALTER DATABASE $(db_name) SET COMPATIBILITY_LEVEL = 130

-- set database options
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
EXEC $(db_name).[dbo].[sp_fulltext_database] @action = 'enable'
END
ALTER DATABASE $(db_name) SET ANSI_NULL_DEFAULT OFF
ALTER DATABASE $(db_name) SET ANSI_NULLS OFF
ALTER DATABASE $(db_name) SET ANSI_PADDING OFF
ALTER DATABASE $(db_name) SET ANSI_WARNINGS OFF
ALTER DATABASE $(db_name) SET ARITHABORT OFF
ALTER DATABASE $(db_name) SET AUTO_CLOSE OFF

ALTER DATABASE $(db_name) SET AUTO_SHRINK OFF
ALTER DATABASE $(db_name) SET AUTO_UPDATE_STATISTICS ON
ALTER DATABASE $(db_name) SET CURSOR_CLOSE_ON_COMMIT OFF
ALTER DATABASE $(db_name) SET CURSOR_DEFAULT  GLOBAL
ALTER DATABASE $(db_name) SET CONCAT_NULL_YIELDS_NULL OFF
ALTER DATABASE $(db_name)SET NUMERIC_ROUNDABORT OFF
ALTER DATABASE $(db_name) SET QUOTED_IDENTIFIER OFF
ALTER DATABASE $(db_name) SET RECURSIVE_TRIGGERS OFF
ALTER DATABASE $(db_name) SET  DISABLE_BROKER
ALTER DATABASE $(db_name) SET AUTO_UPDATE_STATISTICS_ASYNC OFF
ALTER DATABASE $(db_name) SET DATE_CORRELATION_OPTIMIZATION OFF
ALTER DATABASE $(db_name) SET TRUSTWORTHY OFF
ALTER DATABASE $(db_name) SET ALLOW_SNAPSHOT_ISOLATION OFF
ALTER DATABASE $(db_name) SET PARAMETERIZATION SIMPLE
ALTER DATABASE $(db_name) SET READ_COMMITTED_SNAPSHOT OFF
ALTER DATABASE $(db_name) SET HONOR_BROKER_PRIORITY OFF
ALTER DATABASE $(db_name) SET  READ_WRITE
ALTER DATABASE $(db_name) SET RECOVERY SIMPLE
ALTER DATABASE $(db_name) SET  MULTI_USER
ALTER DATABASE $(db_name) SET PAGE_VERIFY CHECKSUM
ALTER DATABASE $(db_name) SET DB_CHAINING OFF
GO
